export default {
  // 获取车辆信息
  GET_CAR_LIST: '/carManageApi/listCarInfo',
  // 添加车辆信息
  ADD_CAR_INFO: '/carManageApi/addCarInfo',
  // 删除车辆信息
  DELETE_CAR_INFO: '/carManageApi/deleteCarInfo',
  // 修改车辆信息
  UPDATE_CAR_INFO: '/carManageApi/updateCarInfo',
  // 获取小区单位信息列表
  GET_COMPANY_LIST: '/yqCompanyManageApi/getEnterpaiseList',
  // 导入车辆EXCEL
  IMPORT_EXCEL: '/carManageApi/importCommunityExcel',
  // 查询人员信息
  GET_PERSONNERL_BY_PHONE: '/personnelManagementApi/getPersonnelByPhone',
  // 获取闸道树
  GET_BARRIER_TREE: '/carManageApi/passage/getBarrierTree',
  // 获取白名单车辆列表
  GET_WHITE_LIST: '/carManageApi/passage/listCarFromWhite',
  // 获取未在白名单列表
  GET_NOT_INWHITE: '/carManageApi/passage/listCarNotInWhite',
  // 添加车辆到白名单
  GET_CAR_TOWHITE: '/carManageApi/passage/addCarToWhite',
  // 删除白名单车辆
  DELETE_CAR_FROMWHITE: '/carManageApi/passage/deleteCarFromWhite',
  // 跟据摄像头获取对应的预警配置
  GET_WARN_CONFIG_BYCAMERAID: '/carManageApi/warnConfig/getWarnConfigByCameraId',
  // 保存预警配置
  SAVE_WARN_CONFIG: '/carManageApi/warnConfig/saveWarnConfig',
  // 获取通行记录车辆
  GET_RECORD_LIST: '/carManageApi/passage/listPassageRecord',
  // 获取预警信息列表
  GET_CAR_WARN_LIST: '/carManageApi/warnConfig/getCarWarnMessageList',
  // 获取预警详情
  GET_CAR_WARN_DETAIL: '/carManageApi/warnConfig/getCarWarnMessageDetail',
  // 查询人员信息列表
  GET_PERSONNERL_LIST: '/personnelManagementApi/getPersonnelList',
  // 获取树组件
  GET_CAR_Tree_List: '/carManageApi/passage/getBarrierTreeList',
};
